### ISSUE TITLE
[Feature] support --recursive in combination with a folder as an argument

### ISSUE THREAD

**Issue by bneijt** [srstevenson/nb-clean#147]
I would like support for recursive to have all the notebooks under a given folder to be considered for cleaning.

`nb-clean clean --recursive banana.ipynb src` would clean both `banana.ipynb` and all `*.ipynb` below the folder `src`.

This relates to issue #140 because that could also be achieved using this option.

**Comment by bneijt** [comment]
During PR discussion the feature was changed to not use a commandline argument but recurse by default for any given path that is a directory.

**Comment by srstevenson** [comment]
Implemented in #148.
