### ISSUE TITLE
Git filter only if file >100MB

### ISSUE THREAD

**Issue by simonmfr** [srstevenson/nb-clean#178]
Hi, is there a flag to set a git filter which only cleans files >100MB (Github file size limit)? Would be much appreciated!

**Comment by srstevenson** [comment]
No, there isn't--nb-clean is primarily designed to remove cell outputs and metadata to reduce the likelihood of merge conflicts and make code review easier, rather than to reduce file size, and so when enabled will filter all notebooks.
