### ISSUE TITLE
Preserve execution count when using `nb-clean`

### ISSUE THREAD

**Issue by thatlittleboy** [srstevenson/nb-clean#221]
Is it possible to retain the cell execution count when using `nb-clean`?

My objective is just to remove metadata, while retaining cell execution count and cell outputs.

I'm not sure if this option exists (not clear to me from reading `nb-clean clean --help`)

I'm using this at the moment

```
nb-clean clean -eo <...ipynb>
```

If it doesn't exist, would you consider adding this option to `nb-clean`? thanks.

**Comment by srstevenson** [comment]
This isn't currently supported, but is something we can add. Are you interested in contributing the PR for this? I suggest passing a new boolean argument `preserve_execution_counts` to the `check_notebook` and `clean_notebook` functions, like we pass `preserve_cell_outputs`.

**Comment by thatlittleboy** [comment]
Sure, I'ld love to give it a go.

**Comment by srstevenson** [comment]
Feel free to push any work in progress as a draft PR, and tag me if you have any questions.
