### ISSUE TITLE
Feature request: preserve notebook metadata

### ISSUE THREAD

**Issue by acroz** [srstevenson/nb-clean#244]
Hi Scott, hope you're well!

I'm interested in using `nb-clean` in a project to fail CI when output is committed in a notebook, but I'd like to be permissive about metadata. I see that the `--preserve-cell-metadata` option allows you to permit cell metadata, but `language_info.version` cannot currently be permitted, if I understand correctly.

Would you consider adding a flag to permit this metadata?

**Comment by srstevenson** [comment]
Hi Andrew, great to hear from you! 👋 This sounds reasonable, I've opened #245 to add this.

**Comment by srstevenson** [comment]
This is now available in [nb-clean 3.2.0](https://pypi.org/project/nb-clean/3.2.0/) which I've uploaded to PyPI.

**Comment by acroz** [comment]
Thanks very much!
