### ISSUE TITLE
Removing the git filter

### ISSUE THREAD

**Issue by liamcoatman** [srstevenson/nb-clean#3]
A useful feature would be the ability to remove the git filter using nb-clean, maybe something like `nb-clean configure-git --uninstall`. Thanks!

**Comment by srstevenson** [comment]
Thanks for the suggestion @liamcoatman! I've implemented this in #4;  after it's merged you'll be able to remove the filter with `nb-clean unconfigure-git`.

**Comment by srstevenson** [comment]
I've released [1.1.0 to PyPI](https://pypi.python.org/pypi/nb-clean/1.1.0) including this.
