### ISSUE TITLE
Cleans ALL the metadata, include any RISE slide information

### ISSUE THREAD

**Issue by wabiloo** [srstevenson/nb-clean#36]
I found that all the cell metadata was removed, not just the cell outputs
![Screenshot 2019-11-22 at 14 09 07](https://user-images.githubusercontent.com/4056263/69432473-ae79d500-0d31-11ea-9ee4-7d885d55040d.png)

**Comment by srstevenson** [comment]
This is by design, but I'd welcome a PR that adds an additional command line flag to preserve metadata if this would be useful.
