### ISSUE TITLE
may it be useful to sometimes preserve metadata?

### ISSUE THREAD

**Issue by volodymyrss** [srstevenson/nb-clean#42]
Thanks for the nice tool!

Unfortunately I find it disrupts some of my notebooks, since I use papermill which relies on [cell tags](https://papermill.readthedocs.io/en/latest/usage-parameterize.html#notebook) (stored in the cell metadata).  And it seems to be something to preserve.

Do metadata often contain something which is not worth saving? If so, would it make sense to have an option for preserve metadata?

**Comment by srstevenson** [comment]
Thanks for the suggestion @volodymyrss! I've implemented this in #43, and released it to PyPI in [nb-clean 1.6.0](https://pypi.org/project/nb-clean/1.6.0/).
