### ISSUE TITLE
Remove python version info

### ISSUE THREAD

**Issue by paulo-coutinho** [srstevenson/nb-clean#49]
Hi,

How to remove python version info?

```
git diff
diff --git a/android/build.ipynb b/android/build.ipynb
index a06f06f..0d103af 100644
--- a/android/build.ipynb
+++ b/android/build.ipynb
@@ -120,7 +120,7 @@
    "name": "python",
    "nbconvert_exporter": "python",
    "pygments_lexer": "ipython3",
-   "version": "3.7.5"
+   "version": "3.8.6"
   }
  },
  "nbformat": 4,
```

Thanks.

**Comment by srstevenson** [comment]
`nb-clean` doesn't clean notebook (as opposed to cell) metadata at present. To remove a specific key like this, I'd use [jq](https://stedolan.github.io/jq/). For your example:
```
jq --indent 1 'del(.metadata.language_info.version)' android/build.ipynb
```
I'm open to add a flag to clean notebook metadata, but disabled by default as removing the notebook metadata causes Jupyter to prompt for a kernel next time the notebook is opened:

![Screenshot 2020-12-31 at 09 43 02](https://user-images.githubusercontent.com/5845679/103405025-950aa580-4b4d-11eb-909a-79617279a97e.png)

**Comment by jbfiot** [comment]
One solution would be to surgically remove only the python version and keep the rest of the notebook metadata. This way:
* a python version update does not make it to the git repo,
* jupyter does prompt for a kernel.

@srstevenson I have implemented it and will open a PR in case you would like to integrate it. 

PS: thanks for this package, staging a clean version of the notebook and keeping the outputs locally is a brilliant idea!
