### ISSUE TITLE
Feedback in cli missing

### ISSUE THREAD

**Issue by 1081** [srstevenson/nb-clean#65]
There is no feedback in the CLI when a command is executed.

For example:

`nb-clean clean notebook.ipynb` --> "notebook.ipynb was successfully clean"

or

`nb-clean check notebook.ipynb` --> "notebook.ipynb is already clean"

**Comment by srstevenson** [comment]
This is consistent with similar tools such as flake8 and autopep8. I'd consider a PR that adds a `-v`/`--verbose` flag adding this behaviour if this would be useful.
